[build]
  command = "npx expo export:web"

[build.environment]
  # Optional: Set NODE_ENV to production for build process
  NODE_ENV = "production"

# Define the npm build script that executes `npx expo export:web`
[[plugins]]
  package = "@netlify/plugin-nextjs"
